#!/usr/bin/env bash
set -mex

if [ -z "${TAILSCALE_KEY}" ]; then
    echo "Missing TAILSCALE_KEY env variable."
    exit 1
fi

tailscaled --fake &
sleep 5
tailscale up -authkey "${TAILSCALE_KEY}" -advertise-tags tag:docker $@

fg